name: black-reviewdog

on: [pull_request]

jobs:
  lint-git-pr-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-black@v3
        with:
          reporter: github-pr-check
          level: error
          fail_on_error: true
          filter_mode: file
