name: Lint black pull request comments

on: [pull_request]

jobs:
  lint-git-pr-comments-action-suggester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: ""
      - name: Comment the git pr
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
          fail_on_error: false
